services:
  - type: web
    name: sap-o2c-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: NEO4J_DATABASE
        sync: false
      - key: REDIS_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
