import type { IntentType, FunctionDef } from '../types/index.js';

export const FUNCTION_REGISTRY: Record<IntentType, FunctionDef[]> = {
  LOOKUP: [
    { name: 'getCustomer', description: 'Get details about a specific customer by ID', params: { customerId: 'string' } },
    { name: 'getOrder', description: 'Get details about a specific sales order', params: { orderId: 'string' } },
    { name: 'getProduct', description: 'Get details about a specific product or material', params: { productId: 'string' } },
    { name: 'getBillingDoc', description: 'Get details about a specific billing document including payment status', params: { billingDocId: 'string' } },
    { name: 'getDelivery', description: 'Get details about a specific delivery document', params: { deliveryId: 'string' } },
  ],
  TRAVERSE: [
    { name: 'traceDocument', description: 'Trace the full O2C flow for a billing document: Sales Order → Delivery → Billing → Journal Entry → Payment', params: { billingDocId: 'string' } },
    { name: 'getOrderDeliveries', description: 'Get all deliveries associated with a sales order', params: { orderId: 'string' } },
    { name: 'getDeliveryBilling', description: 'Get billing documents and payment status for a delivery', params: { deliveryId: 'string' } },
    { name: 'traceOrderJourney', description: 'Trace a sales order complete journey: items ordered, delivered (with actual goods movement date), billed, paid, and cycle times', params: { orderId: 'string' } },
    { name: 'getSalesOrderItemToDeliveryItemJoinInfo', description: 'Explain which edge connects SalesOrderItem to DeliveryItem and the exact raw join fields used', params: {} },
    { name: 'getBusinessPartnerToBillingDocumentPath', description: 'Model the full path from BusinessPartner (Customer) to BillingDocument (BillingHeader), listing hops and join fields', params: {} },
    { name: 'traceSalesOrderToDeliveryAndBilling', description: 'Trace a sales order to outbound deliveries and billing documents with hop keys', params: { orderId: 'string' } },
    { name: 'getO2CGraphSchemaDesign', description: 'Design a property-graph schema for O2C: node labels, key properties, relationships with direction and cardinality', params: {} },
  ],
  AGGREGATE: [
    { name: 'getEntityTypesSummary', description: 'Count distinct node types (entity types) in the dataset graph and list them (excludes auxiliary node types)', params: {} },
    { name: 'getDeliveryGoodsMovementStatusCounts', description: 'Count DeliveryHeader overallGoodsMovementStatus split for A vs C', params: {} },
    { name: 'getBillingItemsReferencingDelivery', description: 'List billing document items that reference a given delivery document ID', params: { deliveryId: 'string' } },
    { name: 'getProductsWithMaxPlantCoverage', description: 'Find max plant coverage across products and count how many products achieve it', params: {} },
    { name: 'getCustomerBilledVsPaidBalance', description: 'Compute total billed (non-cancelled) vs total paid for a customer and outstanding balance', params: { customerId: 'string' } },
    { name: 'getProfitCenterToProductsTrace', description: 'Find dominant profit center in journal entries and trace it to products via ProductPlant.profitCenter', params: {} },
    { name: 'getPaymentsCollectedThisMonth', description: 'Total payments collected in the current month based on Payment.clearingDate', params: {} },
    { name: 'getPaymentsCollectedLastMonth', description: 'Total payments collected in the previous month based on Payment.clearingDate', params: {} },
    { name: 'getSalesRevenueLastMonth', description: 'Total sales revenue from SalesOrder creationDate in the previous month', params: {} },
    { name: 'getOrdersPlacedByCustomer', description: 'List orders placed by a customer via Customer-[:PLACED]->SalesOrder', params: { customerId: 'string' } },
    { name: 'getProductsStoredInPlant', description: 'List products stored in a given plant via ProductPlant links', params: { plantId: 'string' } },
    { name: 'getCancelledInvoicesSummary', description: 'Summarize cancelled invoices via BillingCancellation nodes', params: {} },
    { name: 'getTopProducts', description: 'Get top N products ranked by billing document count or delivery count', params: { metric: 'billing|delivery', limit: 'number' } },
    { name: 'getTopCustomers', description: 'Get top N customers ranked by order count or total order amount', params: { metric: 'orders|amount', limit: 'number' } },
    { name: 'getOrdersByOrg', description: 'Get orders grouped by sales organization, optionally filtered to one org', params: { orgId: 'string|null' } },
    { name: 'getRevenueConcentration', description: 'Get revenue breakdown by customer from active billing documents, with percentage share and total revenue for concentration risk analysis', params: {} },
    { name: 'getActiveBillingTotals', description: 'Get active (non-cancelled) billing docs count + active percentage of total + active total net amount', params: {} },
    { name: 'getTopActiveBillingMonthRevenue', description: 'Find the month with highest active (non-cancelled) billed revenue and compute its % of all active revenue', params: {} },
    { name: 'getTopDeliveriesByProductCount', description: 'Get delivery documents ranked by number of distinct products they contain', params: { limit: 'number' } },
    { name: 'getJournalEntryDistribution', description: 'Get journal entries distributed by customer: total entries, positive vs negative counts, net amount per customer', params: {} },
    { name: 'getPaymentClearingTime', description: 'Get payment clearing time for all paid invoices: days between billing document date and payment clearing date', params: {} },
    { name: 'getPaymentTermsSplit', description: 'Get payment terms (Z001/Z009) split across all sales orders grouped by customer', params: {} },
    { name: 'getBillingDocTypeBreakdown', description: 'Get breakdown of billing documents by type (F2, S1 etc): count, cancelled count, total net amount per type', params: {} },
    { name: 'getPlantRevenueRanking', description: 'Rank all plants by total billed revenue from active (non-cancelled) billing items linked through deliveries', params: {} },
  ],
  DETECT: [
    { name: 'findBrokenFlows', description: 'Find orders/deliveries with incomplete O2C chains: undelivered orders, unbilled deliveries, or unpaid invoices', params: { type: 'undelivered|unbilled|unpaid' } },
    { name: 'getUnpaidInvoices', description: 'Get billing documents with no associated payment, ordered by amount descending', params: { limit: 'number' } },
    { name: 'getDeliveriesNotBilled', description: 'Find delivery documents that were shipped/completed but never had a billing document (invoice) raised — potential revenue leakage', params: {} },
    { name: 'getOrderToPaymentCycleTime', description: 'Order-to-payment cycle time per customer: average days from SalesOrder creation to Payment clearing, with min/max and transaction count. Shows slowest payers first.', params: {} },
    { name: 'getPaymentsWithoutJournalEntries', description: 'Find billing documents where payment was received but no journal entry was posted — reconciliation gap where money moved but books do not match', params: {} },
    { name: 'getCancelledDocs', description: 'Get cancelled billing documents with their related deliveries', params: { limit: 'number' } },
    { name: 'getCustomerBillingSummary', description: 'Get full financial summary for a customer: total billing docs, active vs cancelled, paid vs unpaid, outstanding amount', params: { customerId: 'string' } },
    { name: 'getCancelledAfterPayment', description: 'Find billing documents that were cancelled after payment was already received, with count and total amount', params: {} },
    { name: 'getCustomersWithoutBilling', description: 'Find customers who have never had a billing document raised against them', params: {} },
    { name: 'getProductsNeverDelivered', description: 'Find products that were ordered but never had any delivery', params: {} },
    { name: 'getFullAnomalyReport', description: 'Complete anomaly report: orders not delivered, deliveries not billed, invoices not paid, cancelled after payment, blocked customers with orders, FI posting gaps', params: {} },
    { name: 'getDeliveryFulfillmentRate', description: 'Get delivery fulfillment rate per customer: total items ordered vs items delivered, with order IDs and quantities', params: {} },
    { name: 'getMostExpensiveBillingItem', description: 'Find the most expensive billing items by net amount, including product info, cancellation status, and customer', params: {} },
    { name: 'getUnpaidActiveBillingDocs', description: 'Get active (non-cancelled) billing documents that have NOT been paid, with count, total outstanding amount, and customer breakdown', params: {} },
    { name: 'analyzeBillingCancellationAnomaly', description: 'Analyze anomaly between billing_document_headers and billing_document_cancellations: counts and missing CANCELS edges', params: {} },
  ],
  COMPARE: [
    { name: 'compareCustomerRevenue', description: 'Compare two customers head-to-head: total revenue, billing docs, cancellation rate, unpaid amount', params: { customerId1: 'string', customerId2: 'string' } },
    { name: 'compareCustomerOrders', description: 'Compare two customers by order volume, delivery rate, and order amounts', params: { customerId1: 'string', customerId2: 'string' } },
  ],
  UNKNOWN: [],
};
